# Generated by Django 4.2.4 on 2023-09-02 17:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('price', models.FloatField(default=100, verbose_name='Price')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Product Image')),
                ('type', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=300, null=True, verbose_name='Category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
