# Generated by Django 4.2.4 on 2023-09-04 23:16

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=apps.categories.models.Category),
        ),
    ]
